### ISSUE TITLE
Publish paper describing approach

### ISSUE THREAD

**Issue by p-e-w** [mame/quine-relay#10]
This is more than a cool program – it's a computer science breakthrough! Apparently, you have discovered a method for constructing quines based on an arbitrary blueprint involving any amount of languages.

Please write a technical paper describing your approach. I'm sure you'll have no trouble finding a CS journal that will publish it.

**Comment by mame** [comment]
I'll soon publish a book, ["The world of obfuscated, esoteric, artistic programming"](http://gihyo.jp/book/2015/978-4-7741-7643-7).  The book explains how to write a uroboros quine.  Hence, I proudly close this issue.

It also contains my almost all (about forty) works, including [alphabet-only Ruby program](http://www.slideshare.net/mametter/ruby-esoteric-obfuscated-ruby-programming-5088683),  [radiation-hardened quine](https://github.com/mame/radiation-hardened-quine), etc., and explains many techniques to write such programs.

You can buy my book on [amazon.co.jp](http://www.amazon.co.jp/dp/4774176435). Unfortunately, it is written in Japanese, yet another esoteric language.  I hope anyone can translate to English.

**Comment by chezou** [comment]
:tada: :clap: :tada:

**Comment by KvanTTT** [comment]
Congrats! I'll surely buy it on English.

**Comment by Mikescher** [comment]
yeah, an english version would be cool

**Comment by J-Siu** [comment]
If no English version, I will take Chinese version, if available.
