### ISSUE TITLE
Addition of PHP Framework

### ISSUE THREAD

**Issue by wise-penny** [mame/quine-relay#101]
Hi, I was wondering if you would include PHP -> PASM. Then I can load it into NASM, and I can run it at lightning speed.

**Comment by wise-penny** [comment]
www.github.com/wise-penny/PASM

**Comment by mame** [comment]
In principle, Quine relay uses only languages whose Ubuntu packages are officially available. This limitation is needed for me to make the maintenance easy. Please see the [Criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion).
