### ISSUE TITLE
Guile Error

### ISSUE THREAD

**Issue by JLP04** [mame/quine-relay#102]
The command guile QR.scm > QR.sci in the instructions returns 
Wrong __data_start/_end pair
Aborted (core dumped)

**Comment by mame** [comment]
Sorry but it works for me.

https://travis-ci.org/github/mame/quine-relay/jobs/689518600#L1115

I guess that it is an issue of your installation.  Try to reinstall guile-2.0 or try other Scheme implementation.

**Comment by JLP04** [comment]
It works for me on mac. I think it's a weird issue with guile.
