### ISSUE TITLE
Thue.rb

### ISSUE THREAD

**Issue by JLP04** [mame/quine-relay#103]
The command with thue.rb to generate a typescript file isn't giving any output which is causing the typescript file to be empty.

**Comment by JLP04** [comment]
This issue appears to occuring because of a bad ouput on the following line: 
`ruby vendor/subleq.rb QR.sq > QR.tcl`

**Comment by JLP04** [comment]
The issue appears to be occurring in the tcsh line.

**Comment by mame** [comment]
The expected results are included in https://github.com/mame/quine-relay/tree/spoiler branch.  By comparing these files, you can identify what step produces wrong code.

Currently, quine-relay supports only Ubuntu 20.04.  Are you trying other platform than it?  It is very tough.  It may depend on subtle differences of interpreter versions, so please use the specified versions exactly, check the result step-by-step, and debug it yourself if you find an issue :-)

**Comment by JLP04** [comment]
I am using macOS Catalina, which is probably why it isn't working.
