### ISSUE TITLE
Include TεX in the loop

### ISSUE THREAD

**Issue by FrnchFrgg** [mame/quine-relay#106]
I find it very strange that no implementation of TεX got involved, since people seem to love using TεX in non-intended ways. It is easily available in Ubuntu through texlive, of course.

If I have the time (not likely soon, sadly) I might try to submit a PR to fit it between `tcsh` and `Thue`.

**Comment by mame** [comment]
Thank you for the suggestion.  In fact, I tried adding TeX once.  I might be wrong, but as far as I investigated TeX previously, it seemed impossible to print an arbitrary string to stdout.  So closing this issue temporarily, but if possible, a pull request is really welcome.

**Comment by FrnchFrgg** [comment]
You can open any file for input or output. If stdout is a hard requirement, that would be hard indeed to prevent the standard TεX boiler plate to print.
