### ISSUE TITLE
god is dead and we killed him with quines

### ISSUE THREAD

**Issue by chexo3** [mame/quine-relay#107]
why

**Comment by Abhimanyu8** [comment]
Who else is here from the "Art of Code" video ?

**Comment by Vilquid** [comment]
I'm here from Un code qui s'affiche lui-même ! | Les Quines, TNtube Programming

**Comment by SidBlack** [comment]
I kilka you

**Comment by standardgalactic** [comment]
Can we remove this issue?

**Comment by chexo3** [comment]
Go ahead! This was not a serious issue.
