### ISSUE TITLE
dhall error

### ISSUE THREAD

**Issue by tawan475** [mame/quine-relay#111]
i was using "make" command to run the quine,
after reaching dhall language

the command `dhall text --file QR.dhall > QR.exs`
failed because of `Invalid argument `text'`

changing the command to
`dhall resolve --plain < QR.dhall > QR.exs`
resolve the issue

dhall version `1.19.1-1build2` (newest) on
Ubuntu 20.04.2 LTS

**Comment by mame** [comment]
Dhall 1.19 is so old that it does not support `dhall text` subcommand yet. Please use Dhall 1.32 in Ubuntu 20.10.
