### ISSUE TITLE
It's not making the vendor dir.

### ISSUE THREAD

**Issue by SenpaiBoopboop** [mame/quine-relay#116]
HP-Pavilion:~$ make -C vendor
make: *** vendor: No such file or directory.  Stop.

I'm pretty green but can anyone help?

**Comment by mame** [comment]
The directory is not generated, but provided in the repository. You need to run the command in the top directory of your working copy.

https://github.com/mame/quine-relay/tree/master/vendor

**Comment by SenpaiBoopboop** [comment]
So sorry to bother you, I realized as soon as I sent this that was the case. Your work is amazing, and I'm really enjoying working with it. Thank you so much for your help!

**Comment by SenpaiBoopboop** [comment]
HP-Pavilion:~/git/quine-relay$ lazyk QR.lazy > qr.li
lazyk: command not found
I can't find a way to fix this, it's were I've been stuck for a while. Do you have any advice?

**Comment by SenpaiBoopboop** [comment]
Fix it.
