### ISSUE TITLE
Consider using dotnet compiler for C# instead of outdated mono

### ISSUE THREAD

**Issue by KvanTTT** [mame/quine-relay#128]
https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

**Comment by mame** [comment]
In principle, I'd like to use packages of the ubuntu official repository. See also the [Criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion).
