### ISSUE TITLE
Compilation for Shakespeare Failed

### ISSUE THREAD

**Issue by DE0CH** [mame/quine-relay#129]
I was running this in docker with the command prescribed in readme:

```bash
$ docker build -t qr .
$ docker run --privileged --rm -e CI=true qr
``` 

But it failed everytime at running Shakespeare. 

I know this is docker so the host environment doesn't matter, but still I tried this on multiple hosts and the error seems reproducible.

```
################################
##  7: Shakespeare -> S-Lang  ##
################################

./vendor/local/bin/spl2c < QR.spl > QR.spl.c
gcc -z muldefs -o QR -I ./vendor/local/include -L ./vendor/local/lib QR.spl.c -lspl -lm
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make: *** [Makefile:92: QR.sl] Error 1
```

P.S. Absolutely loving your work!

**Comment by mame** [comment]
Perhaps it's just running out of memory. Compiling for Shakespeare is very memory-consuming. It takes 3 GB of memory on my machine.
