### ISSUE TITLE
Language Request - Modula 2

### ISSUE THREAD

**Issue by Zappo-II** [mame/quine-relay#136]
**Modula 2** is available in ubuntu, via gnu - gm2 compiler
Package should be `gm2-12`...
Is quite esoteric to me since I had to learn it way back in time in my college days, but frankly, I don't seem to remember much of it...

**Comment by mame** [comment]
Like it. Next time I have to remove a language, I would like to add Modula 2.

**Comment by mame** [comment]
Modula-2 has been added. https://github.com/mame/quine-relay/commit/b6dc00456383021c5cdf523e2b1017ca55250dbf Thanks!
