### ISSUE TITLE
Image missing fonts

### ISSUE THREAD

**Issue by Xernisfy** [mame/quine-relay#141]
The langs.png image seems to have been generated without the required fonts.
See commit diff: https://github.com/mame/quine-relay/commit/880a0061be06cc50a33b20fcff4ea4f3c2f29204#diff-dbafb3029b1ce76be2726f78784f03ec879229193519983aa5e518325a6ce79f

Please fix this, the image is really cool!

**Comment by mame** [comment]
Thanks!
