### ISSUE TITLE
Where to find spl2c

### ISSUE THREAD

**Issue by tintin10q** [mame/quine-relay#149]
I can not find the compiler for spl2c

I found [this stackoverflow](https://stackoverflow.com/questions/1948372/compiling-and-executing-the-shakespeare-programming-language-translator-spl2c-on) post about it but the links were dead.

**Comment by mame** [comment]
[spl-1.2.1.tar.gz](https://github.com/mame/quine-relay/blob/master/vendor/spl-1.2.1.tar.gz) is bundled.
