### ISSUE TITLE
Zig support

### ISSUE THREAD

**Issue by Ambyjkl** [mame/quine-relay#151]
Can you add zig support?

**Comment by mame** [comment]
No, because I think there is no Ubuntu official package for zig. See [the language inclusion criteria](https://github.com/mame/quine-relay/wiki/Language-inclusion-criteria).

**Comment by Ambyjkl** [comment]
> No, because I think there is no Ubuntu official package for zig. See [the language inclusion criteria](https://github.com/mame/quine-relay/wiki/Language-inclusion-criteria).

Rip, looks like I'm going to have to pester Ubuntu/Debian to package Zig
