### ISSUE TITLE
add XProc Quine

### ISSUE THREAD

**Issue by innovimax** [mame/quine-relay#55]
XProc implementation : xmlcalabash ( http://xmlcalabash.com/ ) available on github https://github.com/ndw/xmlcalabash1

A possible Quine is https://github.com/innovimax/xproc/blob/master/quine.xpl

**Comment by mame** [comment]
Sorry but it does not satisfy [the criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion).  Please add its package to Ubuntu.  Thank you.
