### ISSUE TITLE
Your Whitespace interpreter isn't quite right.

### ISSUE THREAD

**Issue by rdebath** [mame/quine-relay#65]
It has the 'signed integer labels' bug.

The string of bits use for a label definition is (by the reference interpreter) supposed to be just that. A string of anonymous bits. It does not begin with a sign bit and leading zeros are significant.

For example, using your intermediate form all these are different labels (marks).
```
200 0012
200 012
200 102
200 12
200 2
```

If you want you could say it uses a [bijective positional notation](https://en.wikipedia.org/wiki/Bijective_numeration)

<s>NB: This doesn't have to change the 'quine' but in theory could make the Whitespace step shorter.</s> (Nevermind, just noticed it's a huge print command)

For example, as a quick hack, adding this line seems to work.
```ruby
num = "01" + num if (num && insn != :push && insn != :copy && insn != :slide)
```

**Comment by mame** [comment]
Indeed.  Will fix soon.  Thank you!

**Comment by rdebath** [comment]
Sorry, should have given you a proper bug report; here's a failing example.
This bash command should run it.
```bash
ruby whitespace.rb <( tr -d -c '012' < prime.zs | tr '012' ' \t\n'  )
```


http://www.burghard.info/Code/Whitespace/
This whitespace program generates a few prime numbers.
```
00002000101110120001100002020000110001200010110120001100102000101101120001000002
00011100112000111001020001100101200011000102000110110120001110101200011011102000
10000020001101101200011010012000111001020001110000220112000022001020200001100100
21001210112020000110010021000000121100001210002021022001120220001022001002020000
10112100121010120001022001102020000110010021001210111202000012021110021020000102
02111002100012111000102111100200011001002100000002110000121000202110220011120220
00121000202100220010120220001022001000202000011001002100121010012020000110010021
00011121010102020120100002000100000220110112200101020001210002021000220010012022
00002201122222001011202021011002120020210112200110020222122001220110112000101021
200212
```

**Comment by mame** [comment]
Oops, sorry!

**Comment by mame** [comment]
Well, are labels allowed to be zero-length?  Is [LF][Space][Space][LF] a valid instruction?  [The official site](http://compsoc.dur.ac.uk/whitespace/) is now down...

**Comment by rdebath** [comment]
It's on [archive.org](https://web.archive.org/web/20150623025348/http://compsoc.dur.ac.uk/whitespace/)

It's difficult to be certain as it's not mentioned explicitly in the "Tutorial", However, the original compiler does accept them and the tutorial does describe label as a simple terminated list of spaces and tabs which presumably includes the empty list. So I'd say yes.

**Comment by mame** [comment]
Thank you, I think I managed to fix.  Your prime program works for me.

    $ ruby whitespace.rb <( tr -d -c '012' < prime.zs | tr '012' ' \t\n'  ) 
    prim numbers [2-100]
    2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

**Comment by rdebath** [comment]
Seems to run everything now; [Lost Kingdom](http://rdebath.github.io/LostKingdom/), the [Self interpreter](http://www.burghard.info/Code/Whitespace/) and the [Sudoku solver](https://github.com/hostilefork/whitespacers/tree/master/examples) ... 

I expect the Sudoku one will finish... soon.
