### ISSUE TITLE
Unable to compile QR.c

### ISSUE THREAD

**Issue by xyproto** [mame/quine-relay#68]
When compiling QR.c, I get the following results:

    quine-relay% tcc -o QR QR.c 
    QR.c:2: error: declaration expected

    quine-relay% gcc -o QR QR.c
    QR.c:2:13091: error: expected identifier or ‘(’ before ‘}’ token
          \\\\\\\"s)))\\\").Replace(\\\"~\\\",\\\"\\\\\\\\\\\"));}}\");}");return 0;}}}}
                                                                                     ^
    QR.c:2:13092: error: expected identifier or ‘(’ before ‘}’ token
          \\\\\\\"s)))\\\").Replace(\\\"~\\\",\\\"\\\\\\\\\\\"));}}\");}");return 0;}}}}
                                                                                      ^
    QR.c:2:13093: error: expected identifier or ‘(’ before ‘}’ token
          \\\\\\\"s)))\\\").Replace(\\\"~\\\",\\\"\\\\\\\\\\\"));}}\");}");return 0;}}}}
                                                                                       ^
    quine-relay% clang -o QR QR.c
    QR.c:2:13091: error: extraneous closing brace ('}')
    QR.c:2:13092: error: extraneous closing brace ('}')
    QR.c:2:13093: error: extraneous closing brace ('}')
    3 errors generated.

This is for

    tcc version 0.9.26 (x86-64 Linux)
    gcc (GCC) 5.2.0
    clang version 3.7.0 (tags/RELEASE_370/final)

The preceeding step is using the beef brainfuck compiler: http://kiyuko.org/software/beef

This is for the "50"-branch, on 64-bit Arch Linux.

**Comment by mame** [comment]
The issue occurs at the "boo->bf" stage.  `booi QR.boo` outputs the following warning, which breaks the brainfuck code.

~~~~
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
~~~~

I have no idea why this warning is emitted in Arch Linux.  This is not emitted in Ubuntu.

BTW, I'm not keen to maintain "50" branch.  Could you support master?

**Comment by xyproto** [comment]
Weird message by boo there. Perhaps the runtime engine is too new?

Sure, will switch over to master.

**Comment by mame** [comment]
I've removed Boo from the language list, because Ubuntu 15.10 has a problem to install boo package.  So closing this issue.

FYI: Also Kaya and Falcon are removed.  Instead,  Elixir, Nim, Jq are added.

**Comment by xyproto** [comment]
Awesome! Sounds like a good decision to me.
