### ISSUE TITLE
So does this mean that if I write java program I can translate it to objective C?

### ISSUE THREAD

**Issue by bhargavms** [mame/quine-relay#73]
Or is this only working for your source code, if the source code changes the relay doesn't work?

**Comment by dsoprea** [comment]
It's just a fun trick for what it currently shows.

It's not alchemy.

**Comment by CLOVIS-AI** [comment]
The answer is no, then?

**Comment by mame** [comment]
Regardless of quine-relay, you can translate it to objective C, if you know objective C.
