### ISSUE TITLE
Suggestion: Add a recording through asciinema

### ISSUE THREAD

**Issue by sbrl** [mame/quine-relay#75]
Since very few of us will actually have all the software required to follow this through (and some of us are unable / unwilling) to install it all), I suggest that you record it running with [asciinema](https://asciinema.org/).

**Comment by mame** [comment]
Isn't [Travis CI's log](https://travis-ci.org/mame/quine-relay) enough?

**Comment by sbrl** [comment]
I hadn't realised that this project uses travis. I'll  take a look.
Thanks!

**Comment by mame** [comment]
Closing.
