### ISSUE TITLE
Error on Maxima -> MiniZinc

### ISSUE THREAD

**Issue by chosenken** [mame/quine-relay#76]
Running from the Docker image built locally on Docker for Mac, I get the following error when running `make`:

```
##############################
##  77: Maxima -> MiniZinc  ##
##############################

maxima -q --init-mac=QR.mac > QR.mzn
Makefile:685: recipe for target 'QR.mzn' failed
make: *** [QR.mzn] Error 255
make: *** Deleting file 'QR.mzn'
```

When I run the command `maxima -q --init-mac=QR.mac` I get the following:
```
personality failure 1
```

I verified that the file SHA1 matches.

```
root@bfa052cfb044:/usr/local/share/quine-relay# sha1sum QR.mac
a92ec44504c8ff952bb9adc5d572ae78ec344e2d  QR.mac
root@bfa052cfb044:/usr/local/share/quine-relay# cat SHA1SUMS | grep QR.mac
a92ec44504c8ff952bb9adc5d572ae78ec344e2d *QR.mac
```

**Comment by mame** [comment]
I have not experienced the issue.  I found the following sites with the error message:

https://forums.docker.com/t/issues-with-various-lisp-interpreters/11468

> I ran into following issue when running some Lisp interpreters in Docker for Mac:
>
> *snip*
>
> GCL2 does not start at all: personality failure 1

https://sourceforge.net/p/maxima/mailman/message/35304366/

> docker's default seccomp profile blocks the "personality" syscall, so using
> the default ones + personality should be ok. However, my observation so far
> is that Maxima compiled with sbcl prints a warning on startup, but seems to
> work properly after that. Maxima with gcl, on the other hand, doesn't start
> at all.

https://docs.docker.com/engine/security/seccomp/

> Significant syscalls blocked by the default profile
>
> *snip*
>
> personality	Prevent container from enabling BSD emulation. Not inherently dangerous, but poorly tested, potential for a lot of kernel vulns.

So, I think you are using Seccomp profile for Docker which is incompatible with GCL (Maxima backend).  I guess that you should use `--security-opt seccomp:unconfined` or `--privileged` for docker command.

**Comment by chosenken** [comment]
Thanks!  The `--privileged` flag worked for me.  I'll look at making a section in the readme for running in Docker.
