### ISSUE TITLE
Nemerle language

### ISSUE THREAD

**Issue by NN---** [mame/quine-relay#77]
Can you add Nemerle language ( http://nemerle.org/ ) ?

Examples of quines in Nemerle: ( https://rsdn.org/forum/nemerle/4540959.all )

```nemerle
#pragma indent

def s = <##pragma indent

def s = <#{0}#>

System.Console.WriteLine(s, s)#>

System.Console.WriteLine(s, s)
```

or
 
```nemerle
def s= <#def s= <#{0}#>;System.Console.WriteLine(s, s)#>;System.Console.WriteLine(s, s)
```

Syntax of '<# ... #>' means string.
It is same as " ... " but allows any character and allows recursion.

Thanks.

**Comment by dsoprea** [comment]
@NN Submit a PR with the addition.

**Comment by mame** [comment]
See the [Criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion).  As far as I know, there is no package for Nemerle in Ubuntu official repository.

**Comment by NN---** [comment]
There was once.
I will check how to update it.

**Comment by mame** [comment]
Let me know if Nemerle comes (back?) to Ubuntu.  Closing.  Thank you.
