### ISSUE TITLE
Add YA popular language - Kotlin

### ISSUE THREAD

**Issue by Tradunsky** [mame/quine-relay#78]

**Comment by mame** [comment]
See the [Criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion). As far as I know, there is no package for Kotlin in Ubuntu official repository.

**Comment by Tradunsky** [comment]
According to the fresh news:
https://github.com/KotlinBy/awesome-kotlin/blob/master/app/rss/articles/Ubuntu%20Make%2016.03%20Released%20With%20Eclipse%20JEE%20And%20IntelliJ%20IDEA%20EAP%20Support,%20More.md

**Comment by mame** [comment]
Please read the [Criteria for language inclusion](https://github.com/mame/quine-relay/wiki/Criteria-for-language-inclusion).  I said "I'm too lazy to add PPA."  I actually like Kotlin, but it is not that time yet now.

**Comment by dakshAg** [comment]
https://kotlinlang.org/docs/tutorials/command-line.html

**Comment by dotCipher** [comment]
How about now? 😄

**Comment by mame** [comment]
Recently Ubuntu 19.04 has been released, but it does not include a package for kotlin yet.

https://packages.ubuntu.com/search?keywords=kotlin
