### ISSUE TITLE
*Ouroboros

### ISSUE THREAD

**Issue by macalinao** [mame/quine-relay#79]
Just saying, your description has a typo. :)

**Comment by mame** [comment]
I'm unsure, but the oxford dictionaries say "[uroboros (also ouroboros)](https://en.oxforddictionaries.com/definition/uroboros)".

**Comment by macalinao** [comment]
:o I haven't seen that spelling anywhere before. The wikipedia article is this: https://en.wikipedia.org/wiki/Ouroboros

But sure, i guess it's not a typo haha
