### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by enoua5** [mame/quine-relay#82]
It appears that clojure, dafny, and squirrel3 are no longer in Ubuntu's package lists.

**Comment by mame** [comment]
They are certainly included by the latest version of Ubuntu, 17.04 zesty:

https://packages.ubuntu.com/zesty/clojure
https://packages.ubuntu.com/zesty/dafny
https://packages.ubuntu.com/zesty/squirrel3

I guess your Ubuntu is 16.04 xenial.  It is not old, but quine-relay does not support.
