### ISSUE TITLE
Include intermediate sources

### ISSUE THREAD

**Issue by quchen** [mame/quine-relay#9]
Getting all the compilers/interpreters to run is pretty hard if your repos are outdated, you're using a RPM distro etc. Although many people have forked and compiled this, it would be nice to have the intermediate sources in the main repository.

**Comment by mame** [comment]
I created a "[spoiler](https://github.com/mame/quine-relay/tree/spoiler)" branch.  It will be automatically updated by Travis CI.  Have fun!
