### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by WeileiZeng** [mame/quine-relay#99]
Is there a runnable docker image? I tried several ways, but it is not working for me.

What I have tried:

- Some images on docker hub, which are at least 4 years old.
- git clone and build locally: successfully build, but cannot run. fail and exit at 100: Maxima -> MiniZinc

**Comment by mame** [comment]
> fail and exit at 100: Maxima -> MiniZinc

You need to pass `--privileged` option.  I'm unsure why Maxima requires the option.  [The CI configuration](https://github.com/mame/quine-relay/blob/5a8e02780997da5c3f8a22b5b27ad9fdff7d5dd9/.github/workflows/main.yml#L13) would be useful for you.

**Comment by WeileiZeng** [comment]
Great! I ran it successfully! Thanks!

I saw that file but thought I don't have the privilege. Haha.
